### ISSUE TITLE
Hero section

### ISSUE THREAD

**Issue by kavitappatil** [kavitappatil/LangJo#4]
Story 
As a user
I Want to see the hero section of the page

So That I have a brief intro to the website

-Acceptance Criteria
Given I am  on the landing page
I can see a brief intro to the website
Then I can see more information when I click on learn more button.

-Implementation Notes
Image - ask kavita for the image 
Learn more button - need to create content.

**Comment by PakizeBozkurt** [comment]
Created new hero section.
