### ISSUE TITLE
Beginnner's level

### ISSUE THREAD

**Issue by JanefrancessC** [kavitappatil/LangJo#7]
-Story
As a user
I Want to see an overview of the beginner’s page
So That I can have an understanding of the contents of the page

-Acceptance Criteria
Given I am on the beginner's level page
I can see different videos on different topics
Then I can see the complete video and transcript when I click on one of the learn more buttons.

-Implementation Notes
Videos will be displayed in a grid
Videos must be clicked to play

**Comment by PakizeBozkurt** [comment]
Finished
