### ISSUE TITLE
Tips Blocks

### ISSUE THREAD

**Issue by JanefrancessC** [kavitappatil/LangJo#9]
Story
As a user
I Want to see different tips/links to improve my vocabulary

So That I see read and expand my English knowledge 

-Acceptance Criteria
Given I am redirected to the webpage of the link/tip I click

-Implementation Notes
Users to be redirected to IELTS page 
OR 
We create more contents explaining verbs, adjectives  etc.

**Comment by PakizeBozkurt** [comment]
Finished.
